{"uuid": "c34c9e56-c425-4635-ac81-ffd64aa9f4c4", "children": ["48901caf-b4b1-4a0b-9f77-95d669002350"], "befores": [{"name": "oneTimeSetUp", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"/Users/josemart/PycharmProjects/ViasatPom/tests/conftest.py\", line 16, in oneTimeSetUp\n    driver = wdf.getWebDriverInstance()\n  File \"/Users/josemart/PycharmProjects/ViasatPom/base/webdriverfactory.py\", line 54, in getWebDriverInstance\n    driver = webdriver.Chrome()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/common/service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1557737223737, "stop": 1557737223858}], "start": 1557737223737, "stop": 1557737224185}